### ISSUE TITLE
You forgot add function sendToAll() xD

### ISSUE THREAD

**Issue by Creeperface01** [SavionLegendZzz/HungerGames-fixed#11]

**Comment by andrethegamer** [comment]
ya when ever i set up plugin /hg set and set all spawn when i click the join sign console gives error about   sendToAll() and server shutdown

**Comment by SavionLegendZzz** [comment]
srry will fixm

**Comment by Creeperface01** [comment]
And now is possible only 1 arena right?

**Comment by SavionLegendZzz** [comment]
yeah

**Comment by Creeperface01** [comment]
Do you want add multi aréna support later?

**Comment by SavionLegendZzz** [comment]
yes i will

**Comment by Creeperface01** [comment]
It will be awesome.

**Comment by andrethegamer** [comment]
is  the plugin fixed yet

**Comment by Creeperface01** [comment]
No

**Comment by SavionLegendZzz** [comment]
just updated it

**Comment by SavionLegendZzz** [comment]
please chat in the gitter (info)

**Comment by andrethegamer** [comment]
why when player join it doesnt say match will start in 2 min then 1:30 then 1 min then 10 9 8  7 6 5 4 3 2 1 please make it tell player when match starts
