### ISSUE TITLE
Display when game is starting

### ISSUE THREAD

**Issue by andrethegamer** [SavionLegendZzz/HungerGames-fixed#14]
Hi why when player click the sign to join they get tp to the hg but it dont say when game is starting i  want it to be able to say game is starting in 1;30 something better please help.

**Comment by brandon120** [comment]
How did you even get it to work can you please tell me.

**Comment by andrethegamer** [comment]
Join my server

play.pecraft.tk
19142

**Comment by brandon120** [comment]
It doesn't look like your server is online I put it in exactly.
