### ISSUE TITLE
I found a way to make unlimited matches but I'm not planning on telling anyone

### ISSUE THREAD

**Issue by LinkCraftPE** [SavionLegendZzz/HungerGames-fixed#16]

**Comment by KyleTheHack3r** [comment]
# It's easy.

**Comment by andrethegamer** [comment]
Ok how and why would you post it if you idnt wanna tell anyone

**Comment by andrethegamer** [comment]
And lol How

**Comment by KyleTheHack3r** [comment]
@andrethegamer It could be done by copying and pasting the entire code and changing conflicting vars, and the config.

**Comment by andrethegamer** [comment]
Can you explain more pls

**Comment by SavionLegendZzz** [comment]
I updated the plugin will upload to github soon. You can setup 2 matches

**Comment by KyleTheHack3r** [comment]
This isn't an issue.
