### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MCPotatoCraft** [SavionLegendZzz/HungerGames-fixed#19]
Fatal error: Call to a member function getName() on null in phar:HungerGames_v1.6.phar/src/HG/Main.php on line 1080

**Comment by MCPotatoCraft** [comment]
on HungerGames 1.6

**Comment by MCPotatoCraft** [comment]
close

**Comment by KyleTheHack3r** [comment]
https://github.com/SavionLegendZzz/HungerGames-fixed/releases
